In [1]:
print("hello world")

hello world


In [2]:
# Import the NumPy library for matrix operations
import numpy as np

# Create matrices
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_B = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Matrix Addition
matrix_sum = matrix_A + matrix_B

# Matrix Multiplication
matrix_product = np.dot(matrix_A, matrix_B)

# Matrix Inversion
matrix_inverse_A = np.linalg.inv(matrix_A)

# Display the results
matrix_A, matrix_B, matrix_sum, matrix_product, matrix_inverse_A


(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]),
 array([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]),
 array([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]]),
 array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
        [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
        [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]]))

In [4]:
np.cross(matrix_A,matrix_B)

array([[-10,  20, -10],
       [-10,  20, -10],
       [-10,  20, -10]])

In [5]:
np.linalg.inv(matrix_A)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [6]:
np.linalg.inv(matrix_B)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [7]:
matrix_A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
m1=np.array([[1,2,3],[4,2,5],[2,4,6]])

In [9]:
m1

array([[1, 2, 3],
       [4, 2, 5],
       [2, 4, 6]])

In [10]:
inv(m1)

NameError: name 'inv' is not defined

In [11]:
np.linalg.inv(m1)

LinAlgError: Singular matrix

In [12]:
import sympy as sp
m=m1

In [13]:
m

array([[1, 2, 3],
       [4, 2, 5],
       [2, 4, 6]])

In [14]:
m=Matrix()

NameError: name 'Matrix' is not defined

In [15]:
from sympy import * 

In [16]:
m=Matrix()

In [17]:
m=m1

In [18]:
m

array([[1, 2, 3],
       [4, 2, 5],
       [2, 4, 6]])

In [20]:
m=Matrix([[1,2,3],[4,5,7],[1,1,1]])

In [21]:
M

NameError: name 'M' is not defined

In [22]:
m

Matrix([
[1, 2, 3],
[4, 5, 7],
[1, 1, 1]])

In [23]:
print(m)

Matrix([[1, 2, 3], [4, 5, 7], [1, 1, 1]])


In [24]:
m

Matrix([
[1, 2, 3],
[4, 5, 7],
[1, 1, 1]])

In [25]:
m.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [26]:
m*[0,1,2]

TypeError: can't multiply sequence by non-int of type 'MutableDenseMatrix'

In [27]:
m.multiply([0,1,2])

NotImplemented

In [28]:
m*m

Matrix([
[12, 15, 20],
[31, 40, 54],
[ 6,  8, 11]])

In [29]:
m*3

Matrix([
[ 3,  6,  9],
[12, 15, 21],
[ 3,  3,  3]])

In [30]:
m*Matrix([1,2,3])

Matrix([
[14],
[35],
[ 6]])

In [32]:
h=Matrix([[0,0,1],[1,2,3],[1,1,1]])

In [33]:
h

Matrix([
[0, 0, 1],
[1, 2, 3],
[1, 1, 1]])

In [34]:
j=Matrix([1,2,3])

In [35]:
j

Matrix([
[1],
[2],
[3]])

In [36]:
h*j

Matrix([
[ 3],
[14],
[ 6]])

In [37]:
h.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [38]:
h*Matrix([0,0,1])

Matrix([
[1],
[3],
[1]])

In [39]:
n=Matrix([1,2,3,4],[2,3,4,5],[0,1,2,3])

ValueError: [1, 2, 3, 4] is not an integer

In [40]:
n=Matrix([[1,2,3,4],[2,3,4,5],[0,1,2,3]])

In [41]:
n

Matrix([
[1, 2, 3, 4],
[2, 3, 4, 5],
[0, 1, 2, 3]])

In [42]:
n

Matrix([
[1, 2, 3, 4],
[2, 3, 4, 5],
[0, 1, 2, 3]])

In [43]:
n.rref()

(Matrix([
 [1, 0, -1, -2],
 [0, 1,  2,  3],
 [0, 0,  0,  0]]),
 (0, 1))

In [44]:
n.nullspace()

[Matrix([
 [ 1],
 [-2],
 [ 1],
 [ 0]]),
 Matrix([
 [ 2],
 [-3],
 [ 0],
 [ 1]])]

In [45]:
x=n.nullspace()

In [46]:
x

[Matrix([
 [ 1],
 [-2],
 [ 1],
 [ 0]]),
 Matrix([
 [ 2],
 [-3],
 [ 0],
 [ 1]])]

In [47]:
m

Matrix([
[1, 2, 3],
[4, 5, 7],
[1, 1, 1]])

In [48]:
x

[Matrix([
 [ 1],
 [-2],
 [ 1],
 [ 0]]),
 Matrix([
 [ 2],
 [-3],
 [ 0],
 [ 1]])]

In [49]:
print(x)

[Matrix([
[ 1],
[-2],
[ 1],
[ 0]]), Matrix([
[ 2],
[-3],
[ 0],
[ 1]])]


In [50]:
m

Matrix([
[1, 2, 3],
[4, 5, 7],
[1, 1, 1]])

In [51]:
m.columnspace()

[Matrix([
 [1],
 [4],
 [1]]),
 Matrix([
 [2],
 [5],
 [1]]),
 Matrix([
 [3],
 [7],
 [1]])]

In [52]:
m.transpose().rowspace()

[Matrix([[1, 4, 1]]), Matrix([[0, -3, -1]]), Matrix([[0, 0, 1]])]

In [53]:
m

Matrix([
[1, 2, 3],
[4, 5, 7],
[1, 1, 1]])

In [54]:
m.transpose()

Matrix([
[1, 4, 1],
[2, 5, 1],
[3, 7, 1]])

In [55]:
m.inv()

Matrix([
[-2,  1, -1],
[ 3, -2,  5],
[-1,  1, -3]])

In [56]:
m.nullspace()

[]

In [57]:
m

Matrix([
[1, 2, 3],
[4, 5, 7],
[1, 1, 1]])

In [58]:
m.inv()

Matrix([
[-2,  1, -1],
[ 3, -2,  5],
[-1,  1, -3]])

In [59]:
m.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [60]:
m.columnspace()

[Matrix([
 [1],
 [4],
 [1]]),
 Matrix([
 [2],
 [5],
 [1]]),
 Matrix([
 [3],
 [7],
 [1]])]